### ISSUE TITLE
Expo: Something went wrong running `pod install` in the `ios` directory

### ISSUE THREAD

**Issue by sveinpg** [maplibre/maplibre-react-native#29]
### Steps to Trigger Behavior

1. Create new expo project
2. Install package using `npx expo install @maplibre/maplibre-react-native`
3. After installing this npm package, add the config plugin to the plugins array of your app.json
4. Next, rebuild your app as described in the ["Adding custom native code"](https://docs.expo.io/workflow/customizing/) guide. 

### Expected Behavior

Expected pods to be installed successfully 

### Actual Behavior

```
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: An error occurred while processing the pre-install hook of the Podfile.

undefined method `pre_install' for #<Object:0x00007fac1fe2e6b8>
```

When I run `pod install` manually in ios directory: 

```
Installing maplibre-react-native (9.0.0)
[!] An error occurred while processing the pre-install hook of the Podfile.

undefined method `pre_install' for #<Object:0x00007ff3400eed50>

/Users/svein/skisporet/skisporet-mobile/ios/Podfile:24:in `block (3 levels) in from_ruby'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:162:in `pre_install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:889:in `run_podfile_pre_install_hook'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:877:in `block in run_podfile_pre_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:876:in `run_podfile_pre_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:256:in `block in download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:254:in `download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Version(s) affected

- Platform: IOS

- Device type: [e.g. iPhone6]
- Emulator/ Simulator: [yes/ no]
- Development OS: 12.3.1
- maplibre-react-native Version: 9.0.0 (latest)

### Additional information

generated part of `Podfile`: 

```
# @generated begin pre_installer - expo prebuild (DO NOT MODIFY) sync-c8812095000d6054b846ce74840f0ffb540c2757
  pre_install do |installer|
# @generated begin @maplibre/maplibre-react-native-pre_installer - expo prebuild (DO NOT MODIFY) sync-5a7ed0a20d5aff2d61639bc5bb4fd5551233d57c
    $RNMBGL.pre_install(installer)
# @generated end @maplibre/maplibre-react-native-pre_installer
  end
# @generated end pre_installer
```

**Comment by muehlt** [comment]
Hi, do you have any news on this? I see the exact same behavior.
