### ISSUE TITLE
Error during pod install

### ISSUE THREAD

**Issue by antonsthb** [maplibre/maplibre-react-native#561]
Hi, 

I've been trying to install MapLibre in my app, but I cannot get it to work. Is there something I'm missing here? I've been following the installation guides for both iOS and android. Seems like the native MapLibre module is not being installed.

### Steps to Trigger Behavior

1. Create new React Native project: `npx @react-native-community/cli@latest init MapLibreTest --version 0.74.6`
2. install MapLibre: `npm install @maplibre/maplibre-react-native --save`
3. Follow iOS Instructions (i.e. add line `$MLRN.post_install(installer)` in Podfile and run `pod install`)

### Expected Behavior
Pods should install.
### Actual Behavior
I get the following error during `pod install`:
```
Auto-linking React Native module for target `MapLibreTest`: maplibre-react-native
Framework build type is static library
[Codegen] Adding script_phases to React-Codegen.
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[Codegen] Analyzing /Users/myuser/Workspaces/tmp/MapLibreTest/package.json
[Codegen] Searching for codegen-enabled libraries in the app.
[Codegen] The "codegenConfig" field is not defined in package.json. Assuming there is nothing to generate at the app level.
[Codegen] Searching for codegen-enabled libraries in the project dependencies.
[Codegen] Found react-native


[Codegen] >>>>> Searching for codegen-enabled libraries in react-native.config.js
[Codegen] Processing FBReactNativeSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Processing rncore
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/myuser/Workspaces/tmp/MapLibreTest/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/myuser/Workspaces/tmp/MapLibreTest/node_modules/react-native/ReactCommon
[Codegen] Creating component provider.
[Codegen] Generated provider in: /Users/myuser/Workspaces/tmp/MapLibreTest/node_modules/react-native/React/Fabric
[Codegen] Done.
Analyzing dependencies
Downloading dependencies
Installing React-RCTAppDelegate 0.74.6
Installing React-RCTFabric 0.74.6
Installing maplibre-react-native (10.0.0-alpha.28)
Generating Pods project
Setting USE_HERMES build settings
Setting REACT_NATIVE build settings
[Ccache]: Removing Ccache from CC, LD, CXX & LDPLUSPLUS build settings
[Privacy Manifest Aggregation] Appending aggregated reasons to existing PrivacyInfo.xcprivacy file.
[Privacy Manifest Aggregation] Reading .xcprivacy files to aggregate all used Required Reason APIs.
Setting CLANG_CXX_LANGUAGE_STANDARD to c++20 on /Users/myuser/Workspaces/tmp/MapLibreTest/ios/MapLibreTest.xcodeproj
Pod install took 7 [s] to run
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `post_install' for nil

/Users/myuser/Workspaces/tmp/MapLibreTest/ios/Podfile:39:in `block (3 levels) in from_ruby'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.16.2/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:149:in `message'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:183:in `integrate'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:170:in `install!'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in `run'
/Users/myuser/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/bin/pod:55:in `<top (required)>'
/Users/myuser/.rbenv/versions/3.3.0/bin/pod:25:in `load'
/Users/myuser/.rbenv/versions/3.3.0/bin/pod:25:in `<main>'

[!] [Codegen] warn: using experimental new codegen integration
```

### Minimal Reproducible Example
https://github.com/antonsthb/react-native-map-libre-pod-install-bug

### Environment

- Platform: iOS
- Emulator or Simulator: no
- Development OS: macOS 15.1
- `@maplibre/maplibre-react-native` Version: 10.0.0-alpha.28
- MapLibre Native Version: ?
- `react-native` Verision 0.74.6

**Comment by KiwiKilian** [comment]
Could you please try with the latest beta pre-release? If it still doesn't work, please create a reproduction repository.

**Comment by antonsthb** [comment]
@KiwiKilian Thanks for your response, sorry, I forgot to fill in the latest version, I just updated the issue.

**Comment by KiwiKilian** [comment]
In your repository you are using `$RNML` instead of `$MLRN` in the `Podfile`.

**Comment by antonsthb** [comment]
Huh, no idea how I messed that up, it works now, thanks for the quick response! I'll close this as completed.
