### ISSUE TITLE
Undefined method 'post_install' for nil

### ISSUE THREAD

**Issue by AleksFimin** [maplibre/maplibre-react-native#582]
Hello. I got an error when calling the pod install command. Maybe it's a bug specific to me, I don't know exactly, but I get an error when I add $MLRN.post_install(installer). Without it, pod install works. 

Here's what I'm doing:

1. Create app: npx @react-native-community/cli@latest init MyProject
2. Installing package: npm i @maplibre/maplibre-react-native
3. including needs to podfile: $MLRN.post_install(installer)

My actual podfile:

```
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyProject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    $MLRN.post_install(installer)
  end
end

```

**And I get errors like this:**

```
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method 'post_install' for nil

/Users/alex/Code/React-Native/MyProject/ios/Podfile:40:in 'block (3 levels) in Pod::Podfile.from_ruby'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/podfile.rb:196:in 'Pod::Podfile#post_install!'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:1013:in 'Pod::Installer#run_podfile_post_install_hook'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:1001:in 'block in Pod::Installer#run_podfile_post_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:149:in 'Pod::UserInterface.message'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:1000:in 'Pod::Installer#run_podfile_post_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:337:in 'block (2 levels) in Pod::Installer#create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in 'Pod::Installer::Xcode::PodsProjectWriter#write!'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:336:in 'block in Pod::Installer#create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in 'Pod::UserInterface.section'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:315:in 'Pod::Installer#create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:307:in 'Pod::Installer#generate_pods_project'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:183:in 'Pod::Installer#integrate'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:170:in 'Pod::Installer#install!'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command/install.rb:52:in 'Pod::Command::Install#run'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in 'CLAide::Command.run'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in 'Pod::Command.run'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/gems/cocoapods-1.16.2/bin/pod:55:in '<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/bin/pod:25:in 'Kernel#load'
/opt/homebrew/Cellar/cocoapods/1.16.2_1/libexec/bin/pod:25:in '<main>'
```

**Comment by brentforder** [comment]
I can see that your podfile is doing package linking manually, and you added the `$MLRN.post_install(installer)` line to the right part of your podfile. The docs here assume that you're using auto-linking though: https://github.com/maplibre/maplibre-react-native/blob/main/ios/install.md

$MLRN is nil, and it could be so if the maplibre-react-native package is either not installed yet or not linked properly with your USE_FRAMEWORKS environment variable. I would investigate whether maplibre-react-native is properly linked like your other libraries... If it is, then your build process should at least be downloading the maplibre-react-native.podspec file, which is where the $MLRN variable is defined.

**Comment by AleksFimin** [comment]
I have a podsec file in the library folder

![Image](https://github.com/user-attachments/assets/880615db-e77d-4643-81b5-30253d88bde3)

Project react version: 0.76.5
Version @maplibre/maplibre-react-native: ^10.0.0.0-alpha.28

**Comment by KiwiKilian** [comment]
Can you please try again with the latest beta version? How did you determine, `pod install` within the `ios` directory succeeded?

**Comment by AleksFimin** [comment]
Yes, in the beta version pod install works successfully. The application builds and runs)
